### ISSUE TITLE
web.

### ISSUE THREAD

**Issue by PANOSGRECIA1984** [Wu1z/itunes-search-react#2]
thanks so much where answer meeeeeeeee!!!!ManI love spanish music so muchhhhhhhhhhhhh especially pop balada.could you please make one web for itunes with increase unlimited results for every Song and album?I know very well that itunes have limit 200-300 songs and albums...but you as development I am sure you cannnnnnnnnn!!!!I am searchin one web with unlimited results from itunes many months!!!I AM BEGGING YOU MY FRIEND.UNFORTUNATELY I AM NOT DEVELOPMEN AND I HAVE NO IDEA HOW TO DO IT!!!!GOD BLESS YOU!!!

**Comment by PANOSGRECIA1984** [comment]
my friend someone greek development wants 400 at least euro to make me one web for search music from itunes!!!I am begging you dude make one web with unlimited resultsssssssss!!!pleaseeeeeeeeeeeeeeee man!!!

**Comment by Wu1z** [comment]
In line 33 from index.js remove ('&limit=10') from 'url' variable and be happy!!

**Comment by PANOSGRECIA1984** [comment]
my friend your web not shows songs just 10 and also not shows albums and images.why?
